public enum GameControlCommand {
    UNDO, HINT, NEW, MUSIC, SAVE, LOAD, HOME, EXIT, INVALID, 
    SAVED, UNSAVEABLE, LOADED, UNLOADABLE, WIN, LOSE, DRAW, 
    COMPUTER_STUCK, USER_STUCK, OPPONENT_STUCK,
    REJECT, AGREE;
}
